### ISSUE TITLE
Crash again with latest version

### ISSUE THREAD

**Issue by NicoTine34** [LBLuffy/HoloHud#70]
Application has crashed: C++ exception
mods/Holo/Hooks/Menu/BoxGUIObject.lua:28: bad argument #1 to 'pairs' (table expected, got nil)

SCRIPT STACK

create_sides() @mods/Holo/Hooks/Menu/BoxGUIObject.lua:28
init() lib/managers/menu/boxguiobject.lua:9
new() core/lib/utils/coreclass.lua:35
init() lib/managers/menu/skirmishlandingmenucomponent.lua:356
init() lib/managers/menu/skirmishlandingmenucomponent.lua:393
new() core/lib/utils/coreclass.lua:35
init() lib/managers/menu/skirmishlandingmenucomponent.lua:133
new() core/lib/utils/coreclass.lua:35
create() lib/managers/menu/menucomponentmanager.lua:353
set_active_components() lib/managers/menu/menucomponentmanager.lua:475
original() @mods/base/lua/MenuComponentManager.lua:19
set_active_components() @mods/base/req/core/Hooks.lua:260
core/lib/managers/menu/coremenulogic.lua:89
_execute_action_queue() core/lib/managers/menu/coremenulogic.lua:54
update() core/lib/managers/menu/coremenulogic.lua:64
update() core/lib/managers/menu/coremenumanager.lua:155
update() lib/managers/menumanagerpd2.lua:20
update() lib/setups/setup.lua:854
update() lib/setups/menusetup.lua:336
_update() @mods/base/lua/MenuSetup.lua:6
update() @mods\PocoHud3\poco\common.lua:310
core/lib/setups/coresetup.lua:540

**Comment by Luffyyy** [comment]
Pretty sure I fixed that

**Comment by madladafterhours** [comment]
Sadly no... Game still crashes...

EDIT1: just took a look at the crash log and this is actually the cause of the crash: mods/Holo/Hooks/HUD/AssaultCorner.lua:141: attempt to call method 'is_safehouse_raid' (a nil value)

EDIT2: ^^^^ causes the game to crash the new heist when you move but if you put the mask on right away the game doesnt crash... still investigating the holdout crash thing

EDIT3: I realised that the holdout crash and heist crash are created by 2 different codes. the EDIT1 crash is from ONLY the new heist (other heists seem to be working as usual) and the crash @NicoTine34 experienced was when you try to start a holdout

EDIT4: I was messing around with the code and i think the problem from EDIT1 is fixed. it might have fixed itself tho bc im sure that i put everything back in place after i failed at getting the ui to work... just in case i did fix it somehow lol heres the code that i have rn: https://pastebin.com/Y4nGALH9 to use it go to \PAYDAY 2\mods\Holo\Hooks\Menu open BoxGUIObject.lua with notepad++ or regular notepad, delete all the code inside and paste the code from the link i provided. hope i helped someone even tho im almost sure the game fixed itself lmfao

**Comment by Sydch** [comment]
Still crashing when i am trying to host a Holdout mode.
